version: "3.9"
services:
  db:
    container_name: pet-market-db
    image: "postgres"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pet-market
      POSTGRES_PASSWORD: root
    volumes:
      - "./db:/var/lib/postgresql/data"

volumes:
  db:
