version: "3.9"
services:
  db:
    container_name: pet-market-db
    image: "mysql"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pet-market
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db:/var/lib/mysql"

volumes:
  db: